### PR TITLE
Basic path

### PR DESCRIPTION
**Pull request by langest**
Pathfinding now works. Though we need to implement jump point search for it to make sense.
https://harablog.wordpress.com/2011/09/07/jump-point-search/

### CODE REVIEW

**Comment by langest** [comment]
Now it finds optimal path and can be merged into master. :)

**Comment by ThompZon** [comment]
GLTM, but it seems that it can always move diagonally if that tile is open? (That is, even if there is a tower vertically and horizontal in the diagonal direction it is moving).

**Comment by langest** [comment]
True, didn't think of that. Fixing.

**Comment by ThompZon** [comment]
Sorry for the delay, looks good!

**Pull request merged**
