### PR TITLE
Loading map info from file.

### PR DESCRIPTION
**Pull request by langest**
NOT READY!!!
This update will make it possible to load maps from file located in the info directory.
Todo:
- [x] Loading map from info file
- [x] Actually use the info loaded
- [x] Make sure environment is drawn
- [x] Environment blocks buildings

### CODE REVIEW

**Comment by langest** [comment]
I thinnk it works now.
Please look at the code and test it a little.

**Comment by langest** [comment]
It seems to work now. Though I still have to test to draw out the environment and see if it can affect gameplay.

**Comment by langest** [comment]
I found a bug while adding drawing of environment.
Going to debug it tomorrow.

**Comment by langest** [comment]
Now we can load map from file.
Also found a bug #17  but it seems to be unrelated to the updates here since it is located in GUI.

**Comment by langest** [comment]
Now all environment states != 0 blocks buildings.

**Comment by langest** [comment]
Fixed bug with direction projectiles not working properly with the variable size of the map.

**Comment by ThompZon** [comment]
After aee9f9f towers can now spawn projectiles when standing along the edges, but projectiles can also hit the edge (resulting in the gfx be there after the projectile is destroyed). This must be fixed!

**Comment by langest** [comment]
I cannot recreate this bug.
Try recompiling everything and then check if it is still present.

**Pull request merged**
